[project]
name = "mchlecturesbot"
version = "0.1.0"
description = "Add your description here"
requires-python = "==3.13.11"
dependencies = [
    "arrow>=1.4.0",
    "google-auth>=2.47.0",
    "httpx>=0.28.1",
    "pillow>=12.1.0",
    "py-cord>=2.7.0",
    "python-dotenv>=1.2.1",
    "requests>=2.32.5",
]
